version: '3'

services:
  redis:
    image: redis
    #image: redis:6-alpine
    container_name: cache_redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      # Linux
      #- 'redis:/data'
      - /home/axel/Dev/docker/redis/data:/var/lib/redis/data
      # MacOS
      # - /Users/axel/Dev/docker/redis/data:/var/lib/redis/data

  redis-commander:
    container_name: redis-commander
    image: rediscommander/redis-commander:latest
    # restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  workerui:
    # restart: always
    environment:
      - REDIS_HOSTS=redis://redis:6379
    build:
        context: .
        dockerfile: Dockerfile.worker
    ports:
      - "8003:8003"

  worker:
    # restart: always
    environment:
      - REDIS_HOSTS=redis://redis:6379
      # - REDIS_ADDR=redis:6379
    build:
        context: .
        dockerfile: Dockerfile.dev
    ports:
      - "8001:8001"